### ISSUE TITLE
Publishing fixed Eu notice fails

### ISSUE THREAD

**Issue by jukka-mustonen** [Hankintailmoitukset/hilma-api#114]
Trying to publish fixed EU notice causes error. 

 BadRequest parentId=production_59329 was provided, but projectId was not for a non-dps (parent.ProcedureInformation?.FrameworkAgreement?.IncludesDynamicPurchasingSystem == false) notice. Please provide a projectId.. RequestUri: https://api.hankintailmoitukset.fi/ets/external-api/v1/notice/etsidfixed_67530?parentId=production_59329

**Comment by jannef** [comment]
Pleasy try providing the projectId, as the error message suggests.

**Comment by jannef** [comment]
I took a look, and it does not seem like this has changed recently. When parentId is provided, you should also provide projectId.

Omitting projectId (or providing default value 0) causes a new project to be created for a notice. Providing a projectId puts the newly created notice in a given project. Notices in same project are displayed grouped together in Hilma UI.

![image](https://user-images.githubusercontent.com/14314747/126631733-127601f8-bebb-402f-b3fd-53ad973ae604.png)

Parenting a notice to a notice marks the notices as being part of the same chain. Such as prior information notice and notice; notice and corrigendum; national notice and cancellation etc. When parenting notices, Hilma requires creating the parented notice in the same project.

The exception to this requirement is, as stated in the error message: contract award notice to a DPS can be posted to a separate project.  This exception is created because practically anyone can post a contract award noticce for a DPS, and it's not practical for them to request permissions from the original contracting authority to do so.
