### ISSUE TITLE
When publishing notice Hilma didn't give response

### ISSUE THREAD

**Issue by anttiremes** [Hankintailmoitukset/hilma-api#120]
**ATTENTION!** Fill in the following information but **DO NOT** include any non-public information such as API keys or actual notice data.

**Describe the bug**
And write API gives 404

Warnings
In WRITE API

    SSL: A required certificate is not within its validity period when verifying against the current system clock or the timestamp in the signed file.

**To Reproduce**
- API endpoint that the request was sent to
- HTTP method
- HTTP headers
- sample request payload

**Expected behavior**

**API response**
What is the response from Hilma API? Include the response headers and timestamps.

**Additional context**

**Comment by jannef** [comment]
Hilma tsl certificate renewed today. The automatic renewal took place just 15 minutes prior to expiration. Few subdomains were not configured to use the 'lastest' version of the certificate. This caused some hiccups, since Azure Front Door takes up to 60 minutes to propagate certificate changes.

Adding insult to injury, Azure Api Management services does not support App Service Sertificate IaaA service, that enables automatic certificates renewals - due to a documentation oversight, the APIM sertificate was not swapped: The App Service Certificate managed certificate, which is under the hood stored as Azure Key Vault Secret, needed to be exported and imported back to the very same Azure Key Vault -- but this time as a certificate.

The issue should be resolved now in all environments. I will create a task to figure out a process to avoid this mess when the certificate renews next time 15.11.2022 10:41:10.

**Comment by anttiremes** [comment]
We did not get any Response message from Hilma

**Comment by jannef** [comment]
The update process in APIM servies is taking ages. Please try using the bare default address for the API gateway:

https://hns-hilma-prod-apim.azure-api.net
