### ISSUE TITLE
Validation API concerns

### ISSUE THREAD

**Issue by eduardsmirnov** [Hankintailmoitukset/hilma-api#153]
* in azure environment, could you define which fields are required? For statistics, all fields are optional but validation API says both statistics and mostly all fields inside it are required
* There are no example of statistics json, I had to guess the format
`"hilmaStatistics": {"LOT-0001": {
        "energyEfficiencyConsidered": true,
        "lowCarbon": true,
        "circularEconomy": true,
        "biodiversity": true,
        "sustainableFoodProduction": true,
        "listedGreenCriteriaUsed": false,
        "justWorkingConditions": false,
        "employmentCondition": true,
        "howManyOpportunitiesIsEstimated": -100,
        "codeOfConduct": false,
        "innovationConsidered": false,
        "solutionNewToBuyer": false,
        "solutionNewToMarketOrIndustry": false,
        "smeParticipationConsidered": false
        }}`
* not clear what field name is expected for a lot object, I used "LOT-0001" but any text seems to be allowed there
* I was able to add more than one object for statistics array, however I have only one lot in the form
* I put howManyOpportunitiesIsEstimated = -100, it has been accepted. Is it correct value?
* do you add Hilma specific schematron exceptions manually by some code or they are a part of some schematron rules? if yes, I would like to get that schematron file(s)

**Comment by arinurkkala** [comment]
- HilmaStatistics are not always required. For eg, national notices where contract value is < 60 000€
- Yes, it looks like you figured out the format correctly.
- Clearly we need to set some validations to what the lotId can be in HilmaStatistics. Will create a defect.
- Will create a defect for howManyOpportunitiesIsEstimated  as well.
- They are added manually and we are working on splitting it apart from the TED result. So we don't have schematron rules to provide, but I can provide you with the current validation logic that we have: https://github.com/Hankintailmoitukset/hilma-api/blob/master/validation/NoticeValidator.cs
Note that this is due to change, but hopefully it gives you some insight into the validations.

**Comment by Juhisee** [comment]
closed as resolved
