### ISSUE TITLE
Error when publising notice

### ISSUE THREAD

**Issue by brianshdk** [Hankintailmoitukset/hilma-api#67]
Hi,

We get this error when trying to publish a notice:
Hilma Api: 400 Bad Request Given model specifies PreviousNoticeOjsNumber=2020/S 127-309441, but specified parent notice Id=133591807-1 does not have matching NoticeOjsNumber=2020/S 154-376140! Either omit PreviousNoticeOjsNumber or do not parent the notice.

When we look at TED the two notices are linked correctly:
https://ted.europa.eu/udl?uri=TED:NOTICE:376140-2020:TEXT:EN:HTML&tabId=4

Are we doing something wrong here?

Thanks,
Brian

**Comment by tuomastolvanen** [comment]
Investigating

**Comment by tuomastolvanen** [comment]
The problem is as stated in the error message. Given parent id 2020/S 127-309441 does not have OjsNumber. 2020/S 127-309441. That Ojs Number of notice 133591807. If you are trying to publish another new notice with notice 133591807 as the parent, then you should use it as parentId. If you are publishing a corrigendum for the notice 133591807-1, the you should leave PreviousNoticeOjsNumber empty when making a corrigendum.

**Comment by brianshdk** [comment]
Thanks, turned out the buyer was using the wrong reference.
