### ISSUE TITLE
corrigendum cannot be published to ted if parent notice is rejected

### ISSUE THREAD

**Issue by anttiremes** [Hankintailmoitukset/hilma-api#69]
**ATTENTION!** Fill in the following information but **DO NOT** include any non-public information such as API keys or actual notice data.

**Describe the bug**

**To Reproduce**
Orginal notice
production_30428 published in ted

corrigendum:
production_34353
hilmastatus = 16, tedstatus = 7

new corrigendum cannot be published
BadRequest Notice cannot be published to TED if parent notice is still pending for TED publish. RequestUri: https://api.hankintailmoitukset.fi/ets/external-api/v1/notice/production_34995?parentId=production_34353&projectId=41851

i think ted status is wrong

**Expected behavior**

**API response**
What is the response from Hilma API? Include the response headers and timestamps.

**Additional context**

**Comment by rantati7** [comment]
Ilmoituksen tunnistetiedot
--
Hankinnan nimi | ENMG-TUTKIMUSPALVELUT 2021-2022 (optiot 2023 - 2024)
Lähettäjä | Lapin sairaanhoitopiirin kuntayhtymä
Vastaanottopäivä | 23.10.2020 13:59
Reception Id (sisäinen viite) | 20-530616-001
Viitenumerosi | TEDE0MUT/2020-056668
Submission Id | 20201023-006322
Tiedot
Tiedot, joita haluatte muuttaa kohdassa IV.2.6), eivät vastaa TED-sivustolla (viite 2020/S 197-477771) julkaistun alkuperäisen ilmoituksen tietoja. Oikaistava tieto -kohdassa esitettävän muutettavan tekstin on vastattava täsmällisesti alkuperäisessä ilmoituksessa julkaistua tekstiä, jossa tätä kohtaa ei ole. Olkaa hyvä ja toimittakaa korjausilmoitus, jossa oikaistavat tiedot on ilmoitettu oikein. Kiitos.

**Comment by AlexEngblom** [comment]
In this case your original notice has been published to TED following a rejected corrigendum.

You have two options here:
1. You can either update the existing rejected corrigendum and fix the underlying problem why it was rejected.
2. You can post new corrigendum and reference the **latest published** notice id in the parent id field.

The issue you are facing here is due to invalid parent id which references the rejected notice instead of the original.
