### ISSUE TITLE
Correction notice

### ISSUE THREAD

**Issue by ThomasSiigNoergaard** [Hankintailmoitukset/hilma-api#70]
https://www.hankintailmoitukset.fi/en/public/procurement/42409/notice/56227/overview
Thursday 29.10, 12:18, our customer published a correction notice id 57180 to notice 56227. In HILMA, this original notice is still unchanged. Could you see why this correction notice is not visible in HILMA and has not been published to TED this morning?

**Comment by jannef** [comment]
The corrigendum in question has not been published yet.
It's state is: WaitingToBePublished; while TED-publication state is:  AwaitingTedPublish.

Notices sent to TED are not visible in Hilma, before one of two conditions occur:
- Notice has been published in TED
- More than 48 hours has passed since the notice was sent to TED

Corrigendums are not an exception. This behaviour is mandated by the law, and regrettably cannot be changed.

Thus, the corrigendum will become published in time. After the publication, the original notice will remain as is, but it will have a visible disclaimer and link to the corrected version. Also, the old version is replaced by the corrigendum in the search.

**Comment by ThomasSiigNoergaard** [comment]
Many thanks for the clarification.
