### ISSUE TITLE
Ted rejects all notices

### ISSUE THREAD

**Issue by anttiremes** [Hankintailmoitukset/hilma-api#78]
**ATTENTION!** Fill in the following information but **DO NOT** include any non-public information such as API keys or actual notice data.

**Describe the bug**
Api gives noticenumbers for wrong year. "noticeNumber": "2020-060921", should start 2021

**Comment by tuomastolvanen** [comment]
We have identified the issue related to the notice number update for the notices that we originally created 2020 and send in 2021. The notice number was updated after sending notice to ted which caused them to be rejected by TED because of year 2020. Resending the notice after rejection fixes the problem. We have created a patch for this to avoid future issues and it has been published to production today on 12.1.2021
