### ISSUE TITLE
API response was InternalServerError but notice is recieved and sended to TED

### ISSUE THREAD

**Issue by anttiremes** [Hankintailmoitukset/hilma-api#80]
We have get more than 10 error messages and now TED reports about recieving notice

**To Reproduce**
- API endpoint that the request was sent to
- HTTP method
- HTTP headers
- sample request payload

**Expected behavior**

**API response**
InternalServerError response headers: X-Azure-Ref: 0QnYOYAAAAABuGzmAkMhjQZ6n1gp+cTTCQlJVMzBFREdFMDQxMwAwMTEzMDRiZi1jMzE2LTQ1YTAtYWVhOC0xYWQwMGMyZTZiMjc=  Request-Context: appId=cid-v1:1c7c1805-f4ec-49e2-a8f3-5993b60c63f5  Date: Mon, 25 Jan 2021 07:41:54 GMT  

**Additional context**

**Comment by tuomastolvanen** [comment]
We identified an issue in ETS api that caused the EU notices being set to publish state directly after sending to TED and the operation returned 500 because of internal error. The notices were not published into search index . However some corrigendum notices were visible through original notice for a short period. 

A fix for the issue has been deployed yesterday 25.1. at 20:17 and  all affected notices have been set to original state and they are in peding state in TED. Their ted publish state can be queried throigh ets api with original etsIdentifier.
