### ISSUE TITLE
Why hilma changes status to draft, TED status is AwaitingTedPublish

### ISSUE THREAD

**Issue by anttiremes** [Hankintailmoitukset/hilma-api#82]
**ATTENTION!** Fill in the following information but **DO NOT** include any non-public information such as API keys or actual notice data.

**Describe the bug**
Hilma has changed notice status to draft without reason and TED status is AwaitingTedPublish

**To Reproduce**
example notices
production_40469

"modificationDate": "2021-01-25T14:05:12.5817209",

**Expected behavior**

**API response**
What is the response from Hilma API? Include the response headers and timestamps.

**Additional context**

**Comment by jannef** [comment]
On monday 25.1.2021, there was an incident following publication of new version of Hilma. The affected notices were fixed by hand, which was not done correctly - notices were incorrectly put to draft state.

I have fixed the affected notices, that were not already set to correct state by the TED polling, including the notice in question.
