### ISSUE TITLE
Hilma changes previousojsnumber and TED rejects notice

### ISSUE THREAD

**Issue by anttiremes** [Hankintailmoitukset/hilma-api#83]
**ATTENTION!** Fill in the following information but **DO NOT** include any non-public information such as API keys or actual notice data.

**Describe the bug**
First notice: etsidfixed_42536
sended
"PreviousNoticeOjsNumber": "2020/S 169-409940", -- F01 notice

https://ted.europa.eu/udl?uri=TED:NOTICE:020290-2021:TEXT:FI:HTML

API
"noticeOjsNumber": "2021/S 010-020290",
"previousNoticeOjsNumber": "2020/S 169-409940", --> F01

Second ets: production_44004
sended 
"PreviousNoticeOjsNumber": "2021/S 010-020290",

https://ted.europa.eu/udl?uri=TED:NOTICE:042396-2021:TEXT:FI:HTML

API
"noticeOjsNumber": "2021/S 018-042396",
    "previousNoticeOjsNumber": "2020/S 169-409940",

third ets: production_44640
sended
"PreviousNoticeOjsNumber": "2021/S 010-020290",

API 
"previousNoticeOjsNumber": "2021/S 010-020290",

"changes": [{
      "section": "IV.2.1",
      "label": "Ilmoituksen numero EUVL:ssä",
      "oldText": ["2020/S 169-409940"], --> F01
      "newText": ["2021/S 010-020290"]
    }

**To Reproduce**
- API endpoint that the request was sent to
- HTTP method
- HTTP headers
- sample request payload

**Expected behavior**

**API response**
What is the response from Hilma API? Include the response headers and timestamps.

**Additional context**

**Comment by jannef** [comment]
When making corrigendums, PreviousNoticeOjsNumber should not refer to the OjsNumber of the notice being corrigendumed.  Instead, it is part of the content - it should not change corrigendum to corrigendum, but remain the same for each new version of the notice.

Hilma has some logic in place to prevent API users from making a mistake with PreviousNoticeOjsNumber: notice sent with EtsIdentifier 'production_44004' was automatically fixed, but in the case of corrigendum to corrigendum (production_44640), the issue was not automatically caught.

To avoid this issue, send the correct PreviousNoticeOjsNumber.

On our end, I've added this issue to our backlog. We will stop automatically correcting wrong PreviousNoticeOjsNumbers. Instead, we will be rejecting the notices with bad PreviousNoticeOjsNumber instead, before sending them to TED, as PreviousNoticeOjsNumber is not something TED allows corrigendum notices to change.

**Comment by jannef** [comment]
To clarify, parentId refers to actual previous version of the notice in hilma. This is used to calculate diffs. PreviousNoticeOjsNumber is part of notice content defined by TED - it is logically separate thing from parentId.

**Comment by jannef** [comment]
It has brought to our knowledge, that there is some conflicting information going on about PreviousNoticeOjsNumber.

PreviousNoticeOjsNumber maps to IV.2.1 - previous publication concerning the same procedure - notice number in the OJS. This is notice content that in theory can be corrigendumed. However, in practice, corrigenduming this might actually always lead to the corrigendum being rejected.

Reference to original notice being corrigendumed is defined in section VI.6. This section is filled for the API user, based on the parent based on which the diffs are calculated.
